name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main   # если у тебя главная ветка называется иначе (например master), поменяй здесь

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Copy site files
        run: |
          mkdir public
          cp -r Web-up-up/Web-up/Web/* public/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
